//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSwitchDemo.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageSwitchDemo.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language 的本地化字符串。
        /// </summary>
        public static string Button_Select_Language {
            get {
                return ResourceManager.GetString("Button_Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Label_Current_Language {
            get {
                return ResourceManager.GetString("Label_Current_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The language you are currently using is: 的本地化字符串。
        /// </summary>
        public static string Label_Current_Using {
            get {
                return ResourceManager.GetString("Label_Current_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language 的本地化字符串。
        /// </summary>
        public static string Label_Select_Language {
            get {
                return ResourceManager.GetString("Label_Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string Label_Welcome {
            get {
                return ResourceManager.GetString("Label_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iMarkupExtension Mode 的本地化字符串。
        /// </summary>
        public static string Navigation_iMarkupExtension {
            get {
                return ResourceManager.GetString("Navigation_iMarkupExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item-Index Mode 的本地化字符串。
        /// </summary>
        public static string Navigation_Item_Index {
            get {
                return ResourceManager.GetString("Navigation_Item_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language 的本地化字符串。
        /// </summary>
        public static string Navigation_Select_Language {
            get {
                return ResourceManager.GetString("Navigation_Select_Language", resourceCulture);
            }
        }
    }
}
